version: '3'

services:
  db:
    image: postgis/postgis:13-3.1 # postgres:13
    restart: always
    environment:
      - POSTGRES_DB=locationdb
      - POSTGRES_USER=usertest
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data/upgrade_0.52_hacia_0.53.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres-data:
